name: telegram message on issue comment action
on:
  issue_comment:
    types: created
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on issue comment action
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT }}
          token: ${{ secrets.TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            #${{ github.event_name }}
            @${{ github.actor }} ${{ github.event.action }} [${{ github.event_name }}](${{ github.event.comment.url }})
            on issue: [${{ github.event.issue.title }}](${{ github.event.issue.url }})
            
            `${{ github.event.comment.body }}`
            
            Repository: ${{ github.repository }}
