name: telegram message
on:
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on new issue
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT }}
          token: ${{ secrets.TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            #${{ github.event_name }}
            @${{ github.actor }} ${{ github.event.action }} ${{ github.event_name }}: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})
            Assignees: ${{ github.event.issue.assignee.login }}
            
            `${{ github.event.issue.body }}`
            
            Repository: ${{ github.repository }}
