name: TelegramBridge
  # You may pin to the exact commit or the version.
  uses: GokulDas027/TelegramBridge@1.2
  with:
    # Chat to send: chat id or @channel_name/add to secrets
    chat: 
    # Telegram Bot token/add to secrets
    token: 
    # Job status
    status: # optional, default is ${{ job.status }}
    # Event triggered action
    event: # optional, default is ${{ github.event_name }}
    # Actor who did the action
    actor: # optional, default is ${{ github.actor }}
