name: telegram message pull_request_review_comment
on:
  pull_request_review_comment:
    types: [edited, created, deleted]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on pull_request_review_comment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT }}
          token: ${{ secrets.TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            #${{ github.event_name }}
            @${{ github.actor }} ${{ github.event.action }} [${{ github.event_name }}](${{ github.event.comment.url }})
            on pull_request: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            
            `${{ github.event.comment.body }}`
            
            Repository: ${{ github.repository }}
